apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo 'Hello World!' && sleep 3600"]
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /readiness
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
